version: '3'

services:
  redis:
    image: redis:latest
    container_name: tiger-chat-redis
    ports:
      - "55000:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
