services:
  redis:
    image: redis:latest
    container_name: tiger-chat-redis
    ports:
      - "55000:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    
  minio:
    image: minio/minio
    container_name: tiger-chat-minio
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9001" /data

volumes:
  redis-data:
    driver: local
  minio-data:
    driver: local