version: '3.8'

services:
  tiger-chat:
    build:
      context: ../
      dockerfile: docker/Dockerfile.production
    image: tiger-chat:production
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - ../.env.production
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    networks:
      - tiger-network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - tiger-network

networks:
  tiger-network:
    driver: bridge

volumes:
  redis-data:
